name: angular_barcode
description: Draw Barcode and QrCode with Angular 2
version: 0.5.0
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/angular_barcode

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  angular: 6.0.0-alpha+1
  dart_barcode: ^1.0.1

dev_dependencies:
  build_runner: ^1.6.5
  build_web_compilers: ^2.1.4
    
web:
  compiler:
    debug: dartdevc