name: angular_barcode
description: Draw Barcode with Angular 2
version: 0.0.1
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/angular_barcode

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.0.0
  dart_barcode: ^1.0.0

dev_dependencies:
  browser: ^0.10.0+2
#  test: '>=0.12.0 <0.13.0'

transformers:
  - angular2/transform/codegen:
      platform_directives:
        - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
        - 'package:angular2/common.dart#COMMON_PIPES'
  - angular2/transform/reflection_remover:
      $include:
        - example/angular_barcode.dart