name: angular_barcode
description: Draw Barcode and QrCode with Angular 2
version: 0.0.5
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/angular_barcode

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  dart_barcode: ^1.0.0

dev_dependencies:
  browser: ^0.10.0

transformers:
- angular:
    entry_points:
    - web/main.dart